### PR TITLE
choose "api_key" based on check status

### PR DESCRIPTION
**Pull request by slingler**
Use a different pagerduty api key depending on the sensu alert severity (warning, critical).

### CODE REVIEW

**Comment by analytically** [comment]
Mind adding a paragraph to the README that demonstrates this? Also mind adding a testcase?

**Comment by analytically** [comment]
Bump.

**Comment by zbintliff** [comment]
This is already done on the mutator.
https://github.com/sensu-plugins/sensu-plugins-pagerduty/blob/master/bin/mutator-pagerduty-priority-override.rb#L20

On the client you add teh following hash:

```
pd_override: {
  baseline: {
     warning: key_1,
     critical: key_2
  }
}
```

**Comment by slingler** [comment]
Correct but i found it more convenient to change it once in the sensu handler configuration of pagerduty instead of n-times on each sensu client.

**Comment by zbintliff** [comment]
Then can't the change be just in the mutator? i.e. set the `client[:pager_team]` based on the status?

(we use puppet to configure the clients so didn't think about that)

**Comment by majormoses** [comment]
closing due to inactivity, please open an issue to further to discuss.

**Comment by briancurt** [comment]
Apologies for bumping a very old issue, but I am exactly trying to do this and can't really figure out how to. I have hundreds of clients and would rather not edit the configs for each of them. Is there a way to set the plugin to use a different `api_key` when the event is `warning`, only from the pager_duty escalations file on the Sensu server?

**Pull request closed without merging**
